# Generated by Django 5.0.6 on 2026-06-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Full name of the product e.g. 3-Door Wardrobe with Mirror', max_length=255)),
                ('product_code', models.CharField(help_text='Unique product code e.g. WRD-001. Must be unique across all products.', max_length=100, unique=True)),
                ('active', models.BooleanField(default=True, help_text='Inactive products are hidden from main views but not deleted.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag. Deleted products are hidden everywhere but data is preserved.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_name'],
            },
        ),
    ]
