# Generated by Django 5.0.6 on 2026-06-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        # Remove the global unique constraint from product_code
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(
                help_text='Unique product code e.g. WRD-001. Must be unique across all products.',
                max_length=100
            ),
        ),
        # Add a partial unique index that only applies to non-deleted products
        # This allows soft-deleted products to have their codes reused
        migrations.RunSQL(
            sql='CREATE UNIQUE INDEX products_product_code_unique_active ON products_product(product_code) WHERE is_deleted = 0;',
            reverse_sql='DROP INDEX products_product_code_unique_active;',
        ),
    ]
