# Generated by Django 5.0.6 on 2026-06-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_fix_product_code_soft_delete_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(help_text='Unique product code e.g. WRD-001. Must be unique across all non-deleted products.', max_length=100),
        ),
    ]
