# Generated by Django 5.0.6 on 2026-09-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('registered', 'Registered Dealer'), ('unregistered', 'Small Customer')], default='unregistered', max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='tally_ledger_name',
            field=models.CharField(blank=True, help_text='Exact ledger name as it exists in Tally. Leave blank to use customer name.', max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tally_last_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tally_pushed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tally_pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TallyLedgerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('customer_type', models.CharField(choices=[('registered', 'Registered Dealer'), ('unregistered', 'Small Customer')], max_length=15)),
                ('sales_ledger_name', models.CharField(max_length=200)),
                ('cgst_ledger_name', models.CharField(max_length=200)),
                ('sgst_ledger_name', models.CharField(max_length=200)),
                ('igst_ledger_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'unique_together': {('gst_rate', 'customer_type')},
            },
        ),
    ]
