# Generated by Django 5.0.6 on 2026-09-02 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_customer_customer_type_customer_tally_ledger_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkupTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['percentage'],
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='gst_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='markup_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quotations.markuptier'),
        ),
    ]
