# Generated by Django 5.0.6 on 2026-06-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(help_text='Name of the resource e.g. Teak Wood, Labour, Hardware', max_length=255)),
                ('category', models.CharField(choices=[('Wood', 'Wood'), ('Ply', 'Ply'), ('MDF', 'MDF'), ('Hardware', 'Hardware'), ('Labour', 'Labour'), ('Finishing', 'Finishing'), ('Packing', 'Packing'), ('Other', 'Other')], default='Other', help_text='Category this resource belongs to.', max_length=100)),
                ('unit', models.CharField(help_text='Unit of measurement e.g. SFT, CFT, NOS, KG, RFT', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Current rate per unit. Changing this instantly updates all product costs.', max_digits=12)),
                ('active', models.BooleanField(default=True, help_text='Inactive resources are hidden from BOM selection but data is preserved.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['category', 'resource_name'],
                'unique_together': {('resource_name', 'category')},
            },
        ),
    ]
