# Generated by Django 5.0.6 on 2026-06-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name e.g. Carpentry Materials, Labour Charges', max_length=100, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in dropdowns.')),
                ('active', models.BooleanField(default=True, help_text='Inactive categories are hidden from dropdowns.')),
            ],
            options={
                'verbose_name': 'Resource Category',
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(help_text='Category this resource belongs to.', max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_name',
            field=models.CharField(help_text='Name of the resource e.g. Teak Wood, Carpenter', max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='unit',
            field=models.CharField(help_text='Unit of measurement e.g. cft, sqft, kg, day, nos', max_length=50),
        ),
    ]
