# Generated by Django 5.0.6 on 2026-06-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resourcecategory_alter_resource_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='manual_override_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='When set, this rate is used for all costing — overriding supplier rates. Clear this field to revert to automatic supplier pricing.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='override_reason',
            field=models.CharField(blank=True, help_text="Optional note explaining why the override was set. e.g. 'Better quality', 'Existing credit terms'", max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Master rate. Used as fallback when no supplier links exist.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
