# Generated by Django 5.0.6 on 2026-07-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_manual_override_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='default_unit',
            field=models.CharField(blank=True, help_text="Unit to auto-select in forms when a resource in this category is chosen, e.g. 'cft' or 'sqft'. Leave blank to skip auto-selection for this category.", max_length=10),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='material_type',
            field=models.CharField(choices=[('solid_wood', 'Solid Wood (CFT)'), ('sheet', 'Sheet Material (SFT)'), ('other', 'Other / Not Dimensional')], default='other', help_text="Drives WoodPart formula selection (CFT vs SFT) and the unit auto-default in Resource/BOM forms. Set to 'Solid Wood' for Teak/Country Wood etc, 'Sheet Material' for Ply/MDF/PLPB.", max_length=20),
        ),
    ]
