# Generated by Django 5.0.6 on 2026-07-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_add_category_material_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcecategory',
            name='default_unit',
        ),
        migrations.RemoveField(
            model_name='resourcecategory',
            name='material_type',
        ),
    ]
