# Generated by Django 5.0.6 on 2026-07-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_move_material_type_to_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='material_type',
            field=models.CharField(choices=[('solid_wood', 'Solid Wood (CFT formula)'), ('sheet', 'Sheet Material (SFT formula)'), ('other', 'Other / Not Dimensional')], default='other', help_text="Drives WoodPart formula selection. Set to 'Solid Wood' for Teak/Country Wood (CFT: W×B×L÷divisor), 'Sheet Material' for Plywood/MDF/PLPB (SFT: W×L, no divisor).", max_length=20),
        ),
    ]
