# Generated by Django 5.0.6 on 2026-07-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_move_material_type_to_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='formula_expression',
            field=models.CharField(blank=True, help_text='Optional. A custom formula overriding the default Material Type formula for WoodPart quantity, e.g. "width_in * breadth_in * length_ft * pieces / divisor". Leave blank to use the built-in Solid Wood (CFT) / Sheet (SFT) / Other formula based on Material Type. Evaluated with a safe expression parser — no arbitrary code execution.', max_length=500),
        ),
    ]
