# Generated by Django 5.0.6 on 2026-07-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_resource_formula_expression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='formula_expression',
        ),
    ]