# Generated by Django 5.0.6 on 2026-06-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Company', help_text='Your company name, shown in reports and headers.', max_length=255)),
                ('wood_divisor', models.DecimalField(decimal_places=2, default=144.0, help_text='Divisor used in wood quantity formula: (W × B × L × Pieces) ÷ Divisor. Common values: 144 (inches) or 1728 (cubic inches to CFT).', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
