# Generated by Django 5.0.6 on 2026-07-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='wood_divisor',
        ),
    ]