# Generated by Django 5.0.6 on 2026-09-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_systemconfig_wood_divisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='company_gstin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='company_state',
            field=models.CharField(default='Tamil Nadu', max_length=50),
        ),
    ]
