# Generated by Django 5.0.6 on 2026-06-23 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0002_resourcecategory_alter_resource_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(help_text='Full name of the supplier company.', max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Primary contact number.', max_length=20)),
                ('gst_number', models.CharField(blank=True, help_text='GST registration number.', max_length=20)),
                ('active', models.BooleanField(default=True, help_text='Inactive suppliers are hidden from resource linking.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Any notes about this supplier-resource relationship.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(help_text='The resource being supplied.', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='resources.resource')),
                ('supplier', models.ForeignKey(help_text='The supplier who supplies this resource.', on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Resource Supplier',
                'verbose_name_plural': 'Resource Suppliers',
                'ordering': ['supplier__supplier_name'],
                'unique_together': {('resource', 'supplier')},
            },
        ),
    ]
