# Generated by Django 5.0.6 on 2026-06-23 00:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resourcecategory_alter_resource_category_and_more'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcesupplier',
            options={'ordering': ['-preferred', 'supplier_rate'], 'verbose_name': 'Resource Supplier', 'verbose_name_plural': 'Resource Suppliers'},
        ),
        migrations.AddField(
            model_name='resourcesupplier',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactive links are ignored by the costing engine.'),
        ),
        migrations.AddField(
            model_name='resourcesupplier',
            name='preferred',
            field=models.BooleanField(default=False, help_text="If True, the costing engine uses this supplier's rate. Only one supplier per resource should be preferred."),
        ),
        migrations.AddField(
            model_name='resourcesupplier',
            name='supplier_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="This supplier's rate per unit for this resource.", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='resourcesupplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resourcesupplier',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='resources.resource'),
        ),
        migrations.AlterField(
            model_name='resourcesupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='suppliers.supplier'),
        ),
    ]
