# Generated by Django 5.0.6 on 2026-06-17 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoodPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(help_text='Descriptive name for this part e.g. Top Panel, Side Panel, Back Panel', max_length=255)),
                ('width', models.DecimalField(decimal_places=4, help_text='Width of the piece (in inches or as per your unit system).', max_digits=10)),
                ('breadth', models.DecimalField(decimal_places=4, help_text='Breadth/depth of the piece.', max_digits=10)),
                ('length', models.DecimalField(decimal_places=4, help_text='Length/height of the piece.', max_digits=10)),
                ('pieces', models.PositiveIntegerField(default=1, help_text='How many identical pieces of this part are needed?')),
                ('formula_type', models.CharField(choices=[('standard', 'Standard: (W × B × L × Pieces) ÷ Divisor')], default='standard', help_text='Which formula to use for quantity calculation.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The product this wood part belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='wood_parts', to='products.product')),
                ('resource', models.ForeignKey(help_text='The wood/ply/MDF resource being used.', on_delete=django.db.models.deletion.PROTECT, related_name='wood_parts', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Wood Part',
                'verbose_name_plural': 'Wood Parts',
                'ordering': ['resource__category', 'part_name'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='How many units of this resource does this product need?', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The product this BOM line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='products.product')),
                ('resource', models.ForeignKey(help_text='The resource/material being consumed.', on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='resources.resource')),
            ],
            options={
                'verbose_name': 'BOM Item',
                'verbose_name_plural': 'BOM Items',
                'ordering': ['resource__category', 'resource__resource_name'],
                'unique_together': {('product', 'resource')},
            },
        ),
    ]
