# Generated by Django 5.0.6 on 2026-06-21 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
        ('products', '0003_alter_product_product_code'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woodpart',
            options={'ordering': ['part_name']},
        ),
        migrations.AddField(
            model_name='woodpart',
            name='breadth_unit',
            field=models.CharField(choices=[('in', 'Inches'), ('ft', 'Feet'), ('sqft', 'Square Feet'), ('cft', 'Cubic Feet'), ('mm', 'Millimeters'), ('cm', 'Centimeters'), ('m', 'Meters'), ('nos', 'Numbers')], default='in', max_length=10),
        ),
        migrations.AddField(
            model_name='woodpart',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Optional. Use for 3D parts.', max_digits=10),
        ),
        migrations.AddField(
            model_name='woodpart',
            name='height_unit',
            field=models.CharField(choices=[('in', 'Inches'), ('ft', 'Feet'), ('sqft', 'Square Feet'), ('cft', 'Cubic Feet'), ('mm', 'Millimeters'), ('cm', 'Centimeters'), ('m', 'Meters'), ('nos', 'Numbers')], default='in', max_length=10),
        ),
        migrations.AddField(
            model_name='woodpart',
            name='length_unit',
            field=models.CharField(choices=[('in', 'Inches'), ('ft', 'Feet'), ('sqft', 'Square Feet'), ('cft', 'Cubic Feet'), ('mm', 'Millimeters'), ('cm', 'Centimeters'), ('m', 'Meters'), ('nos', 'Numbers')], default='in', max_length=10),
        ),
        migrations.AddField(
            model_name='woodpart',
            name='width_unit',
            field=models.CharField(choices=[('in', 'Inches'), ('ft', 'Feet'), ('sqft', 'Square Feet'), ('cft', 'Cubic Feet'), ('mm', 'Millimeters'), ('cm', 'Centimeters'), ('m', 'Meters'), ('nos', 'Numbers')], default='in', max_length=10),
        ),
        migrations.AlterField(
            model_name='woodpart',
            name='breadth',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='woodpart',
            name='formula_type',
            field=models.CharField(choices=[('standard', 'Standard (W × B × L × Pcs ÷ Divisor)'), ('area', 'Area (W × L × Pcs ÷ Divisor)'), ('custom', 'Custom')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='woodpart',
            name='length',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='woodpart',
            name='part_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='woodpart',
            name='pieces',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='woodpart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wood_parts', to='products.product'),
        ),
        migrations.AlterField(
            model_name='woodpart',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wood_parts', to='resources.resource'),
        ),
        migrations.AlterField(
            model_name='woodpart',
            name='width',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
