# Generated by Django 5.0.6 on 2026-07-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0004_backfill_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='woodpart',
            name='formula_expression',
            field=models.CharField(blank=True, help_text='Optional. A custom formula for THIS dimension entry only — takes priority over the resource\'s formula and the built-in Material Type formula. E.g. "width_in * breadth_in * length_ft * pieces / 166". Leave blank to fall back to the resource\'s custom formula (if any), then the built-in formula. Evaluated with a safe expression parser — no arbitrary code execution.', max_length=500),
        ),
    ]