# Generated by Django 5.0.6 on 2026-07-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0005_woodpart_formula_expression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woodpart',
            name='breadth_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('cft', 'Cubic Feet'), ('ft', 'Feet'), ('in', 'Inches'), ('m', 'Meters'), ('mm', 'Millimeters'), ('nos', 'Numbers'), ('sqft', 'Square Feet')], default='in', max_length=10),
        ),
        migrations.AlterField(
            model_name='woodpart',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('cft', 'Cubic Feet'), ('ft', 'Feet'), ('in', 'Inches'), ('m', 'Meters'), ('mm', 'Millimeters'), ('nos', 'Numbers'), ('sqft', 'Square Feet')], default='in', max_length=10),
        ),
        migrations.AlterField(
            model_name='woodpart',
            name='length_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('cft', 'Cubic Feet'), ('ft', 'Feet'), ('in', 'Inches'), ('m', 'Meters'), ('mm', 'Millimeters'), ('nos', 'Numbers'), ('sqft', 'Square Feet')], default='in', max_length=10),
        ),
        migrations.AlterField(
            model_name='woodpart',
            name='width_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('cft', 'Cubic Feet'), ('ft', 'Feet'), ('in', 'Inches'), ('m', 'Meters'), ('mm', 'Millimeters'), ('nos', 'Numbers'), ('sqft', 'Square Feet')], default='in', max_length=10),
        ),
    ]
