# Generated by Django 5.0.6 on 2026-07-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0007_merge_duplicate_parts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='part',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name='part',
            name='product',
        ),
    ]
