# Generated by Django 5.0.6 on 2026-06-17 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Original name of the uploaded Excel file.', max_length=255)),
                ('file_path', models.FileField(help_text='Stored copy of the uploaded file.', upload_to='imports/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('products_imported', models.IntegerField(default=0)),
                ('resources_imported', models.IntegerField(default=0)),
                ('bom_rows_imported', models.IntegerField(default=0)),
                ('wood_parts_imported', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, help_text='Any validation errors or warnings during import.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(help_text='Which user uploaded this file.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
