# Generated by Django 5.0.6 on 2026-06-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='import_type',
            field=models.CharField(default='full', help_text="'full' for full workbook, or sheet key for individual.", max_length=50),
        ),
        migrations.AddField(
            model_name='importlog',
            name='suppliers_imported',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importlog',
            name='validation_error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='error_log',
            field=models.TextField(blank=True, help_text='Validation errors or import warnings.'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='file_path',
            field=models.FileField(blank=True, help_text='Stored copy of the uploaded file (optional).', upload_to='imports/'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validation_failed', 'Validation Failed'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
