# Generated by Django 5.0.6 on 2026-07-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importlog_import_type_importlog_suppliers_imported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='parts_imported',
            field=models.IntegerField(default=0),
        ),
    ]
